#include "ft_printf.h"

int		main()
{
	int		res = 0;
	int		myres = 0;

	myres = ft_printf("me%c\n", 'a');
	res = printf("ye%c\n", 'a');
	printf("1[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%3c\n", 'a');
	res = printf("ye%3c\n", 'a');
	printf("2[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%-3c\n", 'a');
	res = printf("ye%-3c\n", 'a');
	printf("3[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%*c\n", 3, 'a');
	res = printf("ye%*c\n", -3, 'a');
	printf("4[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%-*c\n", 3, 'a');
	res = printf("ye%-*c\n", -3, 'a');
	printf("5[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0c\n", 'a');
	res = printf("ye%0c\n", 'a');
	printf("6[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%03c\n", 'a');
	res = printf("ye%03c\n", 'a');
	printf("7[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-3c\n", 'a');
	res = printf("ye%0-3c\n", 'a');
	printf("8[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0*c\n", 3, 'a');
	res = printf("ye%0*c\n", 3, 'a');
	printf("9[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0*c\n", -3, 'a');
	res = printf("ye%0*c\n", -3, 'a');
	printf("10[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-*c\n", 3, 'a');
	res = printf("ye%0-*c\n", 3, 'a');
	printf("11[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-*c\n", -3, 'a');
	res = printf("ye%0-*c\n", -3, 'a');
	printf("12[%d]-[%d]\n", myres, res);
	
	myres = ft_printf("me%.c\n", 'a');
	res = printf("ye%.c\n", 'a');
	printf("13[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.3c\n", 'a');
	res = printf("ye%.3c\n", 'a');
	printf("14[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-3c\n", 'a');
	res = printf("ye%.-3c\n", 'a');
	printf("15[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*c\n", 3, 'a');
	res = printf("ye%.*c\n", 3, 'a');
	printf("16[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*c\n", -3, 'a');
	res = printf("ye%.*c\n", -3, 'a');
	printf("17[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*c\n", 3, 'a');
	res = printf("ye%.-*c\n", 3, 'a');
	printf("18[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*c\n", -3, 'a');
	res = printf("ye%.-*c\n", -3, 'a');
	printf("19[%d]-[%d]\n", myres, res);
	
	myres = ft_printf("me%.0c\n", 'a');
	res = printf("ye%.0c\n", 'a');
	printf("20[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.30c\n", 'a');
	res = printf("ye%.30c\n", 'a');
	printf("21[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-30c\n", 'a');
	res = printf("ye%.-30c\n", 'a');
	printf("22[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*0c\n", 3, 'a');
	res = printf("ye%.*0c\n", 3, 'a');
	printf("23[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*0c\n", -3, 'a');
	res = printf("ye%.*0c\n", -3, 'a');
	printf("24[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*0c\n", 3, 'a');
	res = printf("ye%.-*0c\n", 3, 'a');
	printf("25[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*0c\n", -3, 'a');
	res = printf("ye%.-*0c\n", -3, 'a');
	printf("26[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.03c\n", 'a');
	res = printf("ye%.03c\n", 'a');
	printf("27[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-3c\n", 'a');
	res = printf("ye%.0-3c\n", 'a');
	printf("28[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0*c\n", 3, 'a');
	res = printf("ye%.0*c\n", 3, 'a');
	printf("29[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0*c\n", -3, 'a');
	res = printf("ye%.0*c\n", -3, 'a');
	printf("30[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-*c\n", 3, 'a');
	res = printf("ye%.0-*c\n", 3, 'a');
	printf("31[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-*c\n", -3, 'a');
	res = printf("ye%.0-*c\n", -3, 'a');
	printf("32[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.303c\n", 'a');
	res = printf("ye%.303c\n", 'a');
	printf("33[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-303c\n", 'a');
	res = printf("ye%.-303c\n", 'a');
	printf("34[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.30-3c\n", 'a');
	res = printf("ye%.30-3c\n", 'a');
	printf("35[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-30-3c\n", 'a');
	res = printf("ye%.-30-3c\n", 'a');
	printf("36[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*03c\n", 3, 'a');
	res = printf("ye%.*03c\n", 3, 'a');
	printf("37[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*03c\n", 3, 'a');
	res = printf("ye%.*03c\n", 3, 'a');

	printf("38[%d]-[%d]\n", myres, res);
	return (0);
}
