#include "ft_printf.h"

int		main()
{
	int		res = 0;
	int		myres = 0;
	int		test = 5;

	myres = ft_printf("me%p\n", (void *)test);
	res = printf("ye%p\n", (void *)test);
	printf("1[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%5p\n", (void *)test);
	res = printf("ye%5p\n", (void *)test);
	printf("2[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%-5p\n", (void *)test);
	res = printf("ye%-5p\n", (void *)test);
	printf("3[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%*p\n", 5, (void *)test);
	res = printf("ye%*p\n", -5, (void *)test);
	printf("4[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%-*p\n", 5, (void *)test);
	res = printf("ye%-*p\n", -5, (void *)test);
	printf("5[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0p\n", (void *)test);
	res = printf("ye%0p\n", (void *)test);
	printf("6[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%05p\n", (void *)test);
	res = printf("ye%05p\n", (void *)test);
	printf("7[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-5p\n", (void *)test);
	res = printf("ye%0-5p\n", (void *)test);
	printf("8[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0*p\n", 5, (void *)test);
	res = printf("ye%0*p\n", 5, (void *)test);
	printf("9[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0*p\n", -5, (void *)test);
	res = printf("ye%0*p\n", -5, (void *)test);
	printf("10[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-*p\n", 5, (void *)test);
	res = printf("ye%0-*p\n", 5, (void *)test);
	printf("11[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%0-*p\n", -5, (void *)test);
	res = printf("ye%0-*p\n", -5, (void *)test);
	printf("12[%d]-[%d]\n", myres, res);
	
	myres = ft_printf("me%.p\n", (void *)test);
	res = printf("ye%.p\n", (void *)test);
	printf("13[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.5p\n", (void *)test);
	res = printf("ye%.5p\n", (void *)test);
	printf("14[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-5p\n", (void *)test);
	res = printf("ye%.-5p\n", (void *)test);
	printf("15[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*p\n", 5, (void *)test);
	res = printf("ye%.*p\n", 5, (void *)test);
	printf("16[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*p\n", -5, (void *)test);
	res = printf("ye%.*p\n", -5, (void *)test);
	printf("17[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*p\n", 5, (void *)test);
	res = printf("ye%.-*p\n", 5, (void *)test);
	printf("18[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*p\n", -5, (void *)test);
	res = printf("ye%.-*p\n", -5, (void *)test);
	printf("19[%d]-[%d]\n", myres, res);
	
	myres = ft_printf("me%.0p\n", (void *)test);
	res = printf("ye%.0p\n", (void *)test);
	printf("20[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.50p\n", (void *)test);
	res = printf("ye%.50p\n", (void *)test);
	printf("21[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-50p\n", (void *)test);
	res = printf("ye%.-50p\n", (void *)test);
	printf("22[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*0p\n", 5, (void *)test);
	res = printf("ye%.*0p\n", 5, (void *)test);
	printf("23[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*0p\n", -5, (void *)test);
	res = printf("ye%.*0p\n", -5, (void *)test);
	printf("24[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*0p\n", 5, (void *)test);
	res = printf("ye%.-*0p\n", 5, (void *)test);
	printf("25[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-*0p\n", -5, (void *)test);
	res = printf("ye%.-*0p\n", -5, (void *)test);
	printf("26[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.05p\n", (void *)test);
	res = printf("ye%.05p\n", (void *)test);
	printf("27[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-5p\n", (void *)test);
	res = printf("ye%.0-5p\n", (void *)test);
	printf("28[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0*p\n", 5, (void *)test);
	res = printf("ye%.0*p\n", 5, (void *)test);
	printf("29[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0*p\n", -5, (void *)test);
	res = printf("ye%.0*p\n", -5, (void *)test);
	printf("30[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-*p\n", 5, (void *)test);
	res = printf("ye%.0-*p\n", 5, (void *)test);
	printf("31[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.0-*p\n", -5, (void *)test);
	res = printf("ye%.0-*p\n", -5, (void *)test);
	printf("32[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.505p\n", (void *)test);
	res = printf("ye%.505p\n", (void *)test);
	printf("33[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-505p\n", (void *)test);
	res = printf("ye%.-505p\n", (void *)test);
	printf("34[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.50-5p\n", (void *)test);
	res = printf("ye%.50-5p\n", (void *)test);
	printf("35[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.-50-5p\n", (void *)test);
	res = printf("ye%.-50-5p\n", (void *)test);
	printf("36[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*05p\n", 5, (void *)test);
	res = printf("ye%.*05p\n", 5, (void *)test);
	printf("37[%d]-[%d]\n", myres, res);
	myres = ft_printf("me%.*05p\n", 5, (void *)test);
	res = printf("ye%.*05p\n", 5, (void *)test);
	printf("38[%d]-[%d]\n", myres, res);
	return (0);
}
